server:
  port: 7070

spring:
  application:
    name: luchat-login

  redis:
    host: localhost
    database: 0 #数据库索引
    port: 6379
    jedis:
      pool:
        max-active: 8  #最大连接数
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  #最大空闲连接
        min-idle: 0  #最小空闲连接
    timeout: 3000ms  #超时时间

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/luchat?serverTimezone=UTC
    password: rukia
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid连接池监控默认关闭
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      stat-view-servlet:
        enabled: false
      filter:
        stat:
          enabled: false
      web-stat-filter:
        enabled: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace


